feat: Load ingress HTTPS certificate
pagopa/template-microservizio-k8s pull request #8
Opened 2022-03-14 13:59 UTC by matteocellucci

2022-03-14 14:49 UTC, diegolagospagopa submitted a review, later dismissed

2022-03-15 10:42 UTC, pasqualedevita requested changes

2022-03-15 10:42 UTC, pasqualedevita commented on helm/values-dev.yaml
> +tlsSecretProviderClass: ingress-tls
old?

2022-03-24 13:40 UTC, matteocellucci commented
Closed by #9

2022-03-24 13:40 UTC, closed without merging